# Generated by Django 6.0 on 2025-12-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
